#!/usr/bin/env node
import { parseLongArgs as parseArgs } from "./lib/cli-args.mjs";
import { runSyncProbe } from "./lib/sync-probe.mjs";

import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { resolvePrithaStateRoot, resolveTechscopeRoot } from "./lib/paths.mjs";
import { moduleReadiness } from "./lib/module-readiness.mjs";

const ROOT = resolveTechscopeRoot();
const STATE_ROOT = resolvePrithaStateRoot({ root: ROOT });
const DEFAULT_STATE_PATH = STATE_ROOT === ROOT ? path.join(ROOT, ".techscope-setup.json") : path.join(STATE_ROOT, "setup", "setup.json");
const DEFAULT_ENV_PATH = STATE_ROOT === ROOT ? path.join(ROOT, ".env.local") : path.join(STATE_ROOT, "config", "runtime.env");
const SETUP_VERSION = 1;
const REALTIME_DEFAULT_TOOLS = {
  internet: true,
  memory: true,
  codexCli: true,
};
const REALTIME_TOOL_ENV_NAMES = {
  internet: "internet",
  memory: "memory",
  codexCli: "codex-cli",
};

export function routeTriggerPhrase(text) {
  const value = String(text || "").trim().toLowerCase();
  if (!value) return null;
  if (/(^|\s)(запусти проект|стартуй проект|начни проект|запусти прита|запусти притха|стартуй прита|стартуй притха|начни прита|начни притха|start pritha|start project|setup|first run|bootstrap|start)(\s|$)/iu.test(value)) {
    return {
      id: "first-run-setup",
      workflow: "07_workflows/first-run-setup.md",
      command: "node scripts/bootstrap.mjs prepare --profile local",
    };
  }
  if (/(^|\s)(проверь проект|self test|health)(\s|$)/iu.test(value)) {
    return {
      id: "self-test",
      workflow: "07_workflows/self-test.md",
      command: "node scripts/self-test.mjs",
    };
  }
  if (/(^|\s)(создай агента|new agent|interview)(\s|$)/iu.test(value)) {
    return {
      id: "pritha-interview",
      workflow: "07_workflows/agents-mother.md",
      command: "node scripts/pritha.mjs interview",
    };
  }
  return null;
}



function readJsonIfExists(filePath) {
  if (!existsSync(filePath)) return null;
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function safeRelative(filePath) {
  const rel = path.relative(ROOT, filePath);
  return rel.startsWith("..") ? filePath : rel;
}

function run(command, args, options = {}) {
  const result = runSyncProbe(command, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    timeout: options.timeoutMs || 180000,
    env: { ...process.env, TECHSCOPE_ROOT: ROOT },
  });
  return {
    ok: result.status === 0,
    status: result.status ?? 1,
    stdout: String(result.stdout || "").trim(),
    stderr: String(result.stderr || "").trim(),
  };
}

function mask(value) {
  const text = String(value || "");
  if (!text) return "";
  if (text.length <= 4) return "****";
  return `${"*".repeat(Math.max(4, text.length - 4))}${text.slice(-4)}`;
}

function normalizedRealtimeTools(config) {
  return {
    ...REALTIME_DEFAULT_TOOLS,
    ...(config.realtime?.tools || {}),
  };
}

function realtimeToolEnvValue(config) {
  return Object.entries(normalizedRealtimeTools(config))
    .filter(([, enabled]) => enabled)
    .map(([name]) => REALTIME_TOOL_ENV_NAMES[name] || name)
    .join(",");
}

function envText(values) {
  const lines = [
    "# Generated by Pritha setup. Do not commit this file.",
    `TECHSCOPE_ROOT=${values.TECHSCOPE_ROOT || ROOT}`,
  ];
  for (const [key, value] of Object.entries(values)) {
    if (key === "TECHSCOPE_ROOT") continue;
    if (value !== undefined && value !== null && String(value) !== "") lines.push(`${key}=${value}`);
  }
  return `${lines.join("\n")}\n`;
}

function writePrivateFileAtomic(filePath, content) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  const previous = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
  if (previous === content) return { changed: false, backup: null };
  let backup = null;
  if (previous !== null) {
    backup = `${filePath}.bak`;
    renameSync(filePath, backup);
    chmodSync(backup, 0o600);
  }
  const tempPath = `${filePath}.tmp`;
  writeFileSync(tempPath, content, { mode: 0o600 });
  chmodSync(tempPath, 0o600);
  renameSync(tempPath, filePath);
  chmodSync(filePath, 0o600);
  return { changed: true, backup };
}

function writeJsonAtomic(filePath, payload) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  const content = `${JSON.stringify(payload, null, 2)}\n`;
  const previous = existsSync(filePath) ? readFileSync(filePath, "utf8") : null;
  if (previous === content) return { changed: false };
  const tempPath = `${filePath}.tmp`;
  writeFileSync(tempPath, content);
  renameSync(tempPath, filePath);
  return { changed: true };
}

function defaultConfig() {
  return {
    interfaces: {
      codex: true,
      web: false,
      telegram: false,
      realtime: false,
      obsidian: false,
    },
    web: {
      host: "127.0.0.1",
      port: "3000",
    },
    telegram: {},
    realtime: {
      mode: "always-on",
      confirmedCostPrivacy: false,
      tools: { ...REALTIME_DEFAULT_TOOLS },
    },
    obsidian: {
      vaultPath: ROOT,
    },
    firstAgent: {
      mode: "ask-later",
    },
    qualityGate: true,
  };
}

function mergeConfig(config) {
  const base = defaultConfig();
  return {
    ...base,
    ...config,
    interfaces: { ...base.interfaces, ...(config.interfaces || {}) },
    web: { ...base.web, ...(config.web || {}) },
    telegram: { ...base.telegram, ...(config.telegram || {}) },
    realtime: {
      ...base.realtime,
      ...(config.realtime || {}),
      tools: { ...base.realtime.tools, ...(config.realtime?.tools || {}) },
    },
    obsidian: { ...base.obsidian, ...(config.obsidian || {}) },
  };
}

async function interactiveConfig() {
  const config = defaultConfig();
  const rl = createInterface({ input, output });
  try {
    console.log("Pritha setup: minimal Codex-only configuration is the default.");
    const web = (await rl.question("Enable Web UI? [y/N] ")).trim().toLowerCase();
    config.interfaces.web = web === "y" || web === "yes";
    const telegram = (await rl.question("Enable Telegram connector? [y/N] ")).trim().toLowerCase();
    config.interfaces.telegram = telegram === "y" || telegram === "yes";
    const realtime = (await rl.question("Enable Realtime-2 voice? Cost/privacy warning applies. [y/N] ")).trim().toLowerCase();
    config.interfaces.realtime = realtime === "y" || realtime === "yes";
    if (config.interfaces.realtime) {
      console.log("Warning: always-on realtime can keep the microphone open and may continue billing during silence.");
      console.log("Default realtime tools: internet access, Pritha memory search, Codex CLI sidecar.");
      const confirm = (await rl.question("Continue with realtime always-on? [yes/switch-to-ptt/skip] ")).trim().toLowerCase();
      if (confirm === "skip") config.interfaces.realtime = false;
      if (confirm === "switch-to-ptt") config.realtime.mode = "push-to-talk";
      config.realtime.confirmedCostPrivacy = config.interfaces.realtime;
    }
    const obsidian = (await rl.question("Enable Obsidian vault notes? [y/N] ")).trim().toLowerCase();
    config.interfaces.obsidian = obsidian === "y" || obsidian === "yes";
  } finally {
    rl.close();
  }
  return config;
}

function connectorStatuses(config) {
  const statuses = {
    codex: { status: "configured", detail: "Codex dialog is the default interface." },
    web: { status: config.interfaces.web ? "configured" : "skipped", detail: config.interfaces.web ? `${config.web.host}:${config.web.port}` : "not selected" },
    telegram: { status: config.interfaces.telegram ? "pending" : "skipped", detail: config.interfaces.telegram ? "token validation is non-blocking" : "not selected" },
    realtime: {
      status: config.interfaces.realtime ? (config.realtime.confirmedCostPrivacy ? "configured" : "pending-auth") : "skipped",
      detail: config.interfaces.realtime ? `mode=${config.realtime.mode}` : "not selected",
    },
    obsidian: { status: config.interfaces.obsidian ? "configured" : "skipped", detail: config.interfaces.obsidian ? config.obsidian.vaultPath : "not selected" },
    tailscale: {
      status: "skipped",
      detail: "optional; use node scripts/tailscale-setup.mjs plan/status for private device access",
    },
    codexCli: { status: "skipped", detail: "not required for minimal setup" },
    firstAgent: { status: "pending", detail: config.firstAgent?.mode || "ask-later" },
  };
  return statuses;
}

function realtimeToolStatuses(config, modules) {
  const tools = normalizedRealtimeTools(config);
  const selected = Boolean(config.interfaces.realtime);
  const statuses = {};
  statuses["realtime.tool.internet"] = {
    status: selected && tools.internet ? "configured" : "skipped",
    detail: selected && tools.internet
      ? "enabled as realtime tool surface; live requests remain runtime-gated"
      : "not selected",
  };
  statuses["realtime.tool.memory"] = {
    status: selected && tools.memory
      ? (modules.memory?.status === "configured" ? "configured" : "failed")
      : "skipped",
    detail: selected && tools.memory
      ? (modules.memory?.status === "configured"
          ? "scripts/query-memory.mjs available for lesson/context lookup"
          : `memory module not ready: ${modules.memory?.detail || "unknown"}`)
      : "not selected",
  };
  const codexCliProbe = selected && tools.codexCli ? run("codex", ["--version"], { timeoutMs: 10000 }) : null;
  statuses["realtime.tool.codexCli"] = {
    status: selected && tools.codexCli
      ? (codexCliProbe?.ok ? "configured" : "failed")
      : "skipped",
    detail: selected && tools.codexCli
      ? (codexCliProbe?.ok
          ? `Codex CLI available: ${codexCliProbe.stdout || "version detected"}`
          : "Codex CLI is required for realtime sidecar tasks but was not found or failed to start")
      : "not selected",
  };
  return statuses;
}

function buildEnv(config) {
  const values = { TECHSCOPE_ROOT: ROOT };
  if (config.interfaces.web) {
    values.HOST = config.web.host;
    values.PORT = config.web.port;
  }
  if (config.interfaces.telegram) {
    values.TECHSCOPE_TELEGRAM_BOT_TOKEN = config.telegram.token || "";
    values.TECHSCOPE_TELEGRAM_ALLOWED_USER_IDS = config.telegram.allowedUserIds || "";
  }
  if (config.interfaces.realtime && config.realtime.openaiApiKey) {
    values.OPENAI_API_KEY = config.realtime.openaiApiKey;
  }
  if (config.interfaces.realtime) {
    values.TECHSCOPE_REALTIME_TOOLS = realtimeToolEnvValue(config);
  }
  return values;
}

function statePayload(config, envWrite, quality, statusOverride = null) {
  const sections = connectorStatuses(config);
  const modules = moduleReadiness(ROOT);
  sections.environment = { status: "configured", detail: "env-doctor executed before quality gate" };
  for (const [name, readiness] of Object.entries(modules)) {
    sections[`module.${name}`] = readiness;
  }
  Object.assign(sections, realtimeToolStatuses(config, modules));
  sections.secrets = {
    status: envWrite.changed ? "configured" : "configured-externally",
    detail: envWrite.backup ? `backup created: ${safeRelative(envWrite.backup)}` : "no backup needed",
  };
  sections.qualityGate = { status: quality.ok ? "configured" : "failed", detail: quality.ok ? "pass" : "completed with warnings" };
  const setupIssues = Object.entries(sections)
    .filter(([name, section]) => name.startsWith("realtime.tool.") && ["failed", "pending-auth"].includes(section.status))
    .map(([name, section]) => `${name}: ${section.status}${section.detail ? ` (${section.detail})` : ""}`);
  const warnings = [
    ...(!quality.ok ? [
      "Quality gate returned red. Run `node scripts/self-test.mjs` after fixing the listed checks.",
      quality.stderr || quality.stdout || "quality gate failed",
    ] : []),
    ...setupIssues,
  ];
  return {
    schema: "techscope-setup-state-v1",
    version: SETUP_VERSION,
    status: statusOverride || (warnings.length === 0 ? "completed" : "completed-with-warnings"),
    updated: new Date().toISOString(),
    root: ROOT,
    interfaces: config.interfaces,
    realtime: {
      enabled: Boolean(config.interfaces.realtime),
      mode: config.realtime.mode,
      tools: normalizedRealtimeTools(config),
    },
    modules,
    sections,
    warnings,
    maskedEnv: Object.fromEntries(Object.entries(buildEnv(config)).map(([key, value]) => [key, /TOKEN|KEY|SECRET/i.test(key) ? mask(value) : value])),
  };
}

export async function runSetup(options = {}) {
  const statePath = path.resolve(options.state || DEFAULT_STATE_PATH);
  const envPath = path.resolve(options.env || DEFAULT_ENV_PATH);
  if (options.reset && existsSync(statePath)) renameSync(statePath, `${statePath}.bak`);
  const existing = readJsonIfExists(statePath);
  if (existing?.status === "completed" && !options.reconfigure && !options.reset) {
    if (options.json) console.log(JSON.stringify(existing, null, 2));
    else console.log(`Pritha setup already configured: ${statePath}`);
    return existing;
  }

  const config = options.config
    ? mergeConfig(JSON.parse(readFileSync(path.resolve(options.config), "utf8")))
    : options["non-interactive"]
      ? defaultConfig()
      : await interactiveConfig();

  const envWrite = writePrivateFileAtomic(envPath, envText(buildEnv(config)));
  const skipQuality = options["skip-quality"] || config.qualityGate === false;
  const quality = skipQuality ? { ok: true, stdout: "skipped", stderr: "" } : run("node", ["scripts/quality-gate.mjs"]);
  const state = statePayload(config, envWrite, quality);
  writeJsonAtomic(statePath, state);

  if (options.json) {
    console.log(JSON.stringify(state, null, 2));
  } else {
    console.log(`Pritha setup status: ${state.status}`);
    console.log(`State: ${statePath}`);
    console.log(`Env: ${envPath}`);
    if (!quality.ok) {
      console.log("Completed with warnings:");
      for (const warning of state.warnings) console.log(`- ${warning}`);
    }
  }
  return state;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  if (options.help) {
    console.log(`Usage:
  # Preferred fresh-clone entrypoint:
  node scripts/bootstrap.mjs prepare --profile local
  node scripts/bootstrap.mjs --profile local --start control-center

  # Lower-level setup-state wizard:
  node scripts/setup.mjs
  node scripts/setup.mjs --non-interactive --config tests/fixtures/setup-minimal.json
  node scripts/setup.mjs --reconfigure realtime
  node scripts/setup.mjs --reset
  node scripts/setup.mjs --state <path> --env <path>`);
    return;
  }
  await runSetup(options);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
