'use strict';
const $=id=>document.getElementById(id);
const names={idle:'Готов к работе',searching:'Ищем материалы',fetching:'Читаем источники',drafting:'Пишем черновик',ready:'Готов к проверке',draft_unavailable:'Сборка не завершена',publishing:'Отправляем в Telegram',published:'Опубликован',rejected:'Отклонён',delivery_unknown:'Нужно проверить отправку',legacy_unverified:'Старая запись · отправка не подтверждена'};
const busy=s=>['searching','fetching','drafting'].includes(s);
let publication=null,current=null,latest=null,dirty=false,selected=null,lastSignature='',inflight=false,connected=false;
const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const error=message=>{$('error').textContent=message||'';$('error').hidden=!message;};
let csrfToken='';
async function api(route,body){if(body&&!csrfToken){const info=await api('/api/settings');csrfToken=info.csrfToken;}const r=await fetch(route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Brief-Desk':'1','X-Brief-Desk-CSRF':csrfToken}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Не удалось выполнить действие.');return d;}
function renderDraft(d){current=d;dirty=false;lastSignature=d?d.id+':'+d.revision+':'+d.status:'';
  if(!d){$('editor').innerHTML='<div class="empty">Введите тему, чтобы создать первый бриф.</div>';return;}
  $('editor').innerHTML=`<span class="tag">${d.demo?'ДЕМО · ':''}${escape(names[d.status]||d.status)}</span><p class="muted"><small>${escape(d.topic)}</small></p><h3>${escape(d.title||'Новый бриф')}</h3>${d.error?`<p class="error">${escape(d.error)}</p>`:''}<ul class="bullets">${(d.bullets||[]).map(b=>'<li>'+escape(b)+'</li>').join('')}</ul>${(d.sources||[]).length?'<h4>Источники</h4><ol class="sources">'+d.sources.map(s=>{const u=typeof s==='string'?s:s.url;return /^https:\/\//.test(u)?`<li><a href="${escape(u)}" target="_blank" rel="noopener noreferrer">${escape(s.title||u)}</a>${s.excerpt?' · выдержка':''}</li>`:'<li>'+escape(u)+'</li>';}).join('')+'</ol>':''}${(d.scannerWarnings||[]).map(w=>'<p class="note">'+escape(w)+'</p>').join('')}${d.status==='ready'?'<details id="edit-fields"><summary>Редактировать текст</summary><label for="edit-title">Заголовок</label><input id="edit-title" maxlength="200" value="'+escape(d.title)+'"><label for="edit-bullets">Пункты — каждый с новой строки</label><textarea id="edit-bullets" rows="10">'+escape(d.bullets.join('\n'))+'</textarea><div class="actions"><button id="save">Сохранить правки</button></div></details><div class="actions"><button id="publish" class="publish">Опубликовать в Telegram</button><button id="reject">Отклонить</button></div><small>Ничего не отправляется без вашего подтверждения.</small>':busy(d.status)?'<p class="muted">Можно оставаться на странице: результат появится автоматически.</p>':''}`;
  if(d.status==='ready'){
    for(const el of [$('edit-title'),$('edit-bullets')])el.addEventListener('input',()=>{dirty=true;$('publish').disabled=true;});
    $('save').onclick=()=>action(async()=>{const r=await api('/api/edit',{draftId:current.id,revision:current.revision,title:$('edit-title').value,bullets:$('edit-bullets').value.split('\n').map(s=>s.trim()).filter(Boolean)});renderDraft(r.draft);});
    $('reject').onclick=()=>action(async()=>{await api('/api/reject',{draftId:current.id});selected=null;await refresh();});
    $('publish').disabled=!latest?.configuration?.telegram;
    $('publish').onclick=()=>{publication={draftId:current.id,revision:current.revision,approved:true};$('confirm-title').textContent=current.title;$('publication-dialog').showModal();};
  }
}
async function action(fn){error('');try{await fn();}catch(e){error(e.message);}}
function renderHistory(d){$('draft-history').innerHTML=d.drafts.length?d.drafts.slice(0,12).map(x=>`<div class="history-item"><button data-draft="${escape(x.id)}">${escape(x.title||x.topic)}</button><small>${escape(names[x.status]||x.status)} · ${new Date(x.createdAt).toLocaleString('ru',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<small class="muted">Пока нет брифов</small>';document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>action(async()=>{if(dirty)throw new Error('Сначала сохраните изменения текущего брифа.');const r=await api('/api/draft?id='+encodeURIComponent(b.dataset.draft));selected=r.draft.id;renderDraft(r.draft);}));$('topic-history').innerHTML=d.topics.slice().reverse().map(t=>'<div class="topic-item">'+escape(t)+'</div>').join('')||'Пока пусто';}
async function refresh(){const d=await api('/api/status');latest=d;connected=true;$('connection').textContent='● На связи';$('progress').textContent=busy(d.status)?names[d.status]+'…':names[d.status]||'';$('build').disabled=busy(d.status)||inflight;$('cancel').hidden=!busy(d.status);$('footer').textContent='Модель: '+d.configuration.model+' · Telegram: '+(d.configuration.telegram?'подключён':'не настроен')+' · Публикация только после подтверждения';if(d.configuration.publicUrl){const a=document.createElement('a');a.href=d.configuration.publicUrl;a.textContent='Открыть через Tailscale';a.style.marginLeft='12px';$('footer').append(a);}if(!dirty){let show=d.draft;if(selected&&selected!==show?.id)show=(await api('/api/draft?id='+encodeURIComponent(selected))).draft;const sig=show?show.id+':'+show.revision+':'+show.status:'';if(sig!==lastSignature||!current)renderDraft(show);}renderHistory(d);}
$('build-form').onsubmit=e=>{e.preventDefault();if(inflight)return;action(async()=>{const topic=$('topic').value.trim();if(!topic)throw new Error('Введите тему.');if(dirty)throw new Error('Сохраните изменения текущего брифа.');inflight=true;$('build').disabled=true;try{await api('/api/brief',{topic,requestId:crypto.randomUUID()});selected=null;lastSignature='';await refresh();}finally{inflight=false;$('build').disabled=busy(latest?.status);}});};
$('cancel').onclick=()=>action(async()=>{await api('/api/cancel',{});await refresh();});
$('dismiss-publish').onclick=()=>$('publication-dialog').close();
$('confirm-publish').onclick=()=>action(async()=>{const button=$('confirm-publish');button.disabled=true;try{await api('/api/approve',publication);$('publication-dialog').close();lastSignature='';await refresh();}finally{button.disabled=false;}});
async function tick(){try{await refresh();}catch(e){connected=false;$('connection').textContent='Нет связи · повторяем';}finally{setTimeout(tick,2000);}}tick();

async function loadSettings(){const d=await api('/api/settings');csrfToken=d.csrfToken;$('key-source').value=d.keySource;$('nd-model').value=d.model;$('tg-chat').value=d.chatId;$('nd-key').value='';$('tg-token').value='';$('key-status').textContent=d.neuraldeepConfigured?'NeuralDeep подключён':'Подключите ключ в Pritha или выберите собственный';$('tg-status').textContent=d.telegramReady?'Telegram настроен':d.telegramConfigured?'Укажите назначение':'Telegram не настроен';}
$('settings-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('/api/settings',{keySource:$('key-source').value,model:$('nd-model').value,neuraldeepKey:$('nd-key').value,telegramToken:$('tg-token').value,chatId:$('tg-chat').value.trim()});await loadSettings();await refresh();$('settings-result').textContent='Сохранено';});};
for(const [button,field] of [['remove-nd','removeNeuraldeepKey'],['remove-tg','removeTelegramToken']])$(button).onclick=()=>action(async()=>{await api('/api/settings',{[field]:true});await loadSettings();await refresh();});
for(const [button,provider] of [['check-nd','neuraldeep'],['check-tg','telegram']])$(button).onclick=()=>action(async()=>{$('settings-result').textContent='Проверяем…';try{const d=await api('/api/settings/'+provider+'/check',{});$('settings-result').textContent=d.destination||d.bot||'Подключение доступно';}catch(e){$('settings-result').textContent=e.message;}});
$('test-tg').onclick=()=>$('test-dialog').showModal();$('cancel-test').onclick=()=>$('test-dialog').close();
$('confirm-test').onclick=()=>action(async()=>{$('confirm-test').disabled=true;try{await api('/api/settings/telegram/test',{approved:true});$('settings-result').textContent='Тестовое сообщение отправлено';}finally{$('confirm-test').disabled=false;$('test-dialog').close();}});
$('open-demo').onclick=()=>action(async()=>{if(dirty)throw new Error('Сначала сохраните правки.');await api('/api/demo',{});selected=null;lastSignature='';await refresh();});
action(loadSettings);
