export type CreationAction = 'approve_contract'|'approve_outcome'|'continue'|'pause'|'cancel'|'revise_proposal';
export type CreationRequest = { requestId:string; expectedRevision:number; action:CreationAction; actor?:'user'|'codex-operator'; authorizationBasis?:string; reason?:string };
export type CreationDocument = {path:string;hash:string;text:string;issues:string[]};
export type CreationJobView = {
  jobId:string;chatId:string;agentId:string;revision:number;generation?:number;proposalRevisionPending?:boolean;phase:string;status:string;releaseSha:string;
  versions:{source:string|null;runtime:string|null;execution:string|null;sourceDirty:boolean};
  contract:CreationDocument|null;outcome:CreationDocument|null;
  approvals:Record<string,{hash:string;actor:string;approvedAt:string;authorizationBasis?:string}>;
  blocker:{code:string;message:string}|null;checkpoint:unknown;
  budget:{tokensUsed:number;maxTokens:number;activeMs:number;maxActiveMs:number;unknownAttempts:string[];maxIterations:number;repeatedFailures:number};
  observedUsage?:{knownMinimumTokens:number;unfinalizedTokens:number;unknownRequests:number};
  preparation?:{phase:{brief:number;research:number};phaseRemaining:{brief:number;research:number};total:number;remaining:number;
    requests:number;requestsRemaining:number;pendingRequests:number;unknownRequests:number;deliveryProtected:number;availableForDelivery:number|null;
    limits:{briefTokens:number;researchTokens:number;totalTokens:number;maxRequests:number};research:{checked:string[];remaining:string[]}|null};
  context?:{bytes:number|null;packetBytes:number|null;reservation:number|null;outputLimit:number|null;freshLimit:number;rotationLimit:number;hardLimit:number;requestMode?:string;sourceBytes?:number};
  nextDispatch?:{status:string;reason:string};
  deliveryRunId:string|null;actions:Record<CreationAction,boolean>;
  delivery?:{adopted:boolean;acceptance?:string;head?:string|null};agentCardUrl?:string|null;
};
export function creationReleaseIdentity(root:string):CreationJobView['versions'];
export function creationDraftRoot(stateRoot:string,instanceId:string,chatId:string):string;
export function reconcileCreationArtifacts(job:any,options:{root:string;stateRoot:string}):any;
export function creationJobView(job:any,options:{root:string;stateRoot:string;executionSha?:string|null}):CreationJobView;
export type CreationApprovalCheckpoint = 'intent_recorded'|'canonical_written'|'outcome_receipt_written'|'receipt_completed';
export function approveCreationDocument(job:any,kind:'contract'|'outcome',request:CreationRequest,options:{root:string;stateRoot:string;onApprovalCheckpoint?:(checkpoint:CreationApprovalCheckpoint)=>void}):any;
export function creationPrompt(job:any):string;
export function creationHostStep(job:any,options:{root:string;stateRoot:string;model:string;effort:string|null;sourceRoot?:string;sourceRevision?:string}):Promise<any>;
